
# H2 Database
spring.datasource.url=jdbc:h2:mem:pulsedeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Hugging Face
huggingface.api.token=hf_your_token_here
huggingface.model.url=https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3